name: Lint Code

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:

      - name: 🔍 Vérification du code (lint)
        run: npx eslint . --ext .js
